# Generated by Django 2.0.7 on 2018-07-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_document_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='owner',
            new_name='auther',
        ),
    ]
