# Generated by Django 2.0.7 on 2018-07-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180721_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='auther',
            new_name='author',
        ),
    ]
