# Generated by Django 2.0.7 on 2018-07-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180722_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='author',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
